version: '3'

services:
  postgres:
    container_name: db
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=devconnect'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'