spring:
  datasource:
    url: jdbc:postgresql://db:5432/devconnect
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password: root
    baseline-description: "init"
    baseline-version: 1

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem